### PR TITLE
Update CRoaring submodule to latest 0.2.60 release

### PR DESCRIPTION
**Pull request by antiochp**
https://github.com/lemire/CRoaringUnityBuild/commit/dc77aa29b4260dba8fa1d27d4764cec5825da708

`cargo build` and `cargo test` both run successfully against this version.

### CODE REVIEW

**Comment by antiochp** [comment]
Ping @saulius.

**Comment by saulius** [comment]
Thanks!

**Comment by antiochp** [comment]
Hey @saulius do you have an ETA for a new release?

**Comment by saulius** [comment]
Hi @antiochp , just published 0.3.9 with updated CRoaring.

**Pull request merged**
