### PR TITLE
Update version on bindgen dep

### PR DESCRIPTION
**Pull request by malthe**
`bindgen = ">= 0.37, <= 0.49"`

### CODE REVIEW

**Comment by saulius** [comment]
Thanks!

**Comment by saulius** [comment]
Btw, what's wrong with versions above `0.49`? I don't see any stable releases.

**Comment by malthe** [comment]
@saulius, I just thought it might be good to put an upper bound on a tested version? I'm not really that knowledgeable about dependency management to be honest.

**Comment by saulius** [comment]
I think we can leave the constraint, but generally I don't think we should limit this unless someone experiences any issues with newer dependency versions. In that case I'd just try to resolve those issues.

**Pull request merged**
